# Generated by Django 3.1.7 on 2021-09-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rcq',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Medida Quadril (cm)'),
        ),
    ]
