# Generated by Django 3.1.7 on 2021-09-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20210905_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rcq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Medida Quadril (cm)'),
        ),
    ]
