# Generated by Django 3.1.7 on 2021-09-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_auto_20210905_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='d1',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Subescapular'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Tricipital'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d3',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Peitoral'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d4',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Axilar Média'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d5',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Supra-Ilíaca'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d6',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Cutânea Abdominal'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d7',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Femural Médio'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='d_soma',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Soma Dobras'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dc',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='gordura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Dobras Cutâneas'),
        ),
    ]
