# Generated by Django 3.1.7 on 2021-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_auto_20210905_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='dc',
        ),
        migrations.AddField(
            model_name='aluno',
            name='dc1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dc2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dc3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dctotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d_soma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Soma Dobras'),
        ),
    ]
