# Generated by Django 3.1.7 on 2021-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_auto_20210906_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='d1',
            field=models.FloatField(null=True, verbose_name='Subescapular'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d2',
            field=models.FloatField(null=True, verbose_name='Tricipital'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d3',
            field=models.FloatField(null=True, verbose_name='Peitoral'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d4',
            field=models.FloatField(null=True, verbose_name='Axilar Média'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d5',
            field=models.FloatField(null=True, verbose_name='Supra-Ilíaca'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d6',
            field=models.FloatField(null=True, verbose_name='Cutânea Abdominal'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d7',
            field=models.FloatField(null=True, verbose_name='Femural Médio'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='d_soma',
            field=models.FloatField(null=True, verbose_name='Soma Dobras'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc1',
            field=models.FloatField(null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc2',
            field=models.FloatField(null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc3',
            field=models.FloatField(null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dctotal',
            field=models.FloatField(null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='gordura',
            field=models.FloatField(null=True, verbose_name='Dobras Cutâneas'),
        ),
    ]
