# Generated by Django 3.1.7 on 2021-09-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_auto_20210906_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='d_soma',
            field=models.FloatField(blank=True, null=True, verbose_name='Soma Dobras'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc1',
            field=models.FloatField(blank=True, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc2',
            field=models.FloatField(blank=True, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dc3',
            field=models.FloatField(blank=True, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dctotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='gordura',
            field=models.FloatField(blank=True, null=True, verbose_name='Dobras Cutâneas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.FloatField(verbose_name='Idade'),
        ),
    ]
